ElevenNote.Web/Controllers/NoteController.cs
using ElevenNote.Models;
using ElevenNote.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElevenNote.Web.Controllers
{
    //we want to be able to only have a logged in user see these pages 
    // let's let MVC framework do this work with this annotation
    // this says when you get a request make sure that the user is authenticated, if not direct ot login page
    [Authorize]
    public class NoteController : Controller
    {
        public ActionResult Index()
        {
            //bringing in the model from the model layer
            //Notice that we passed in the array
            // think of how we use string[] 
            // NoteListItem is a data type and we want to pass in an empty array of zero to have something to iterate over.
            //var model = new NoteListItem[0]; we dont need this anymore after we created our service 

            //GetUserId is an extension so we need to do a ctrl dot(.)
            var service = CreateNoteService();

            // model is a Ienumerable for data from our service #mindblown
            var model = service.GetNotes();

            return View(model);
        }

        //We aren't giving any data, we are going to be creating data with this
        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NoteCreate model)
        {
            //this check if the data is incorrect and the server is bueno
            if (!ModelState.IsValid) return View(model);

            var service = CreateNoteService();


            //This if handles if everything is bueno
            if (service.CreateNote(model))
            {
                //we need to share this data to another view, to be available by the index

                //ViewBag.SaveResult = "Your note was created";

                // this is a small wraper on top of the session
                // TempData works across views. 
                // TempData is a dictionary, so we create a key of SaveResults with the value of a string.
                TempData["SaveResult"] = "Your note was created";
                //when you read a value it removes it from the session, so its only temporarialy stored
                return RedirectToAction("Index");
            };

            //the if statement above happens after submission was valid 
            //this model state is allowing us to pass an error message to our view.
            // this is a great case if the server isn't responding, thats when it would reach this statement
            ModelState.AddModelError("", "Your note could not be created");
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = CreateNoteService();
            var model = svc.GetNoteById(id);
            return View(model);
        }

        //lower case id is important because that the convention used in the route
        public ActionResult Edit(int id)
        {
            var svc = CreateNoteService();
            var detail = svc.GetNoteById(id);
            var model =
                new NoteEdit
                {
                    NoteId = detail.NoteId,
                    Title = detail.Title,
                    Content = detail.Content
                };

            return View(model);
        }
        //we need to post the data from the edit page!
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, NoteEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if(model.NoteId != id)
            {
                ModelState.AddModelError("", "Note ID is mis-matched");
                return View(model);
            }

            var service = CreateNoteService();
            if (service.UpdateNote(model))
            {
                TempData["SaveResult"] = "Your note was updated";
                return RedirectToAction("Index");
            };

            TempData["SaveResult"] = "Your note was not updated";
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            var svc = CreateNoteService();
            var model = svc.GetNoteById(id);
            return View(model);
        }

        [HttpPost]
        //this action overrides the name of the action method that it's called on
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var svc = CreateNoteService();
            var model = svc.DeleteNote(id);

            TempData["SaveResults"] = "Your note was deleted!";

            return RedirectToAction("Index");
        }

        private NoteService CreateNoteService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new NoteService(userId);
            return service;
        }
    }
}

ElevenNote.Web/Controllers/WebApi/NoteController.cs
using ElevenNote.Models;
using ElevenNote.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace ElevenNote.Web.Controllers.WebApi
{
    //we don't want just anyone to change our notes, so we want to only allow autourize users.
    //this will not redirect to the login page, it will just say unauthourize.
    [Authorize]

    //one thing that is different about webapi is the routing! we need to place attribute base routing
    // this sets up a separate url in the application to see the api route
    [RoutePrefix("api/Note")]
    public class NoteController : ApiController
    {
        //notice the Note controller is inheriting from the ApiController, which in this case is IHttpContent,and IDisposable
        [Route("{id}/Star")]
        [HttpPut]
        public bool ToggleStarOn(int id) => SetStarState(id, true);

        
        [Route("{id}/Star")]
        [HttpDelete]
        public bool ToggleStarOff(int id) => SetStarState(id, false);
        
        private bool SetStarState(int noteId, bool newState)
        {
            NoteService service = CreateNoteService();

            var detail = service.GetNoteById(noteId);

            var updatedNote =
                new NoteEdit
                {
                    NoteId = detail.NoteId,
                    Title = detail.Title,
                    Content = detail.Content,
                    IsStarred = newState
                };

            return service.UpdateNote(updatedNote);
        }

        private NoteService CreateNoteService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new NoteService(userId);
            return service;
        }
    }
}

ElevenNote.Web/Views/Note/Create.cshtml
@model ElevenNote.Models.NoteCreate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NoteCreate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ElevenNote.Web/Views/Note/Delete.cshtml
@model ElevenNote.Models.NoteDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NoteDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NoteId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoteId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedUtc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index", "Note", new { @class = "btn btn-default"})
        </div>
    }
</div>

ElevenNote.Web/Views/Note/Details.cshtml
@model ElevenNote.Models.NoteDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>NoteDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NoteId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoteId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedUtc)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new {id = Model.NoteId}) |
    @Html.ActionLink("Back to List", "Index")
</p>

ElevenNote.Web/Views/Note/Edit.cshtml
@model ElevenNote.Models.NoteEdit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>   


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NoteEdit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.NoteId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoteId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoteId, "", new { @class = "text-danger" })
            </div>
        </div>*@
        @Html.HiddenFor( model => model.NoteId)
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ElevenNote.Web/Views/Note/Index.cshtml
@model IEnumerable<ElevenNote.Models.NoteListItem>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@*
    We created this list view using the add button from the controller
    and was prebuilt by VS #powerful

*@
<p>
    @Html.ActionLink("Create New", "Create")
</p>

@if (TempData.ContainsKey("SaveResult"))
{
    <div class="alert alert-success alert-dismissible fade-in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @TempData["SaveResult"]
    </div>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NoteId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsStarred)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NoteId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsStarred, new { Id = item.NoteId })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedUtc)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.NoteId }) |
                @Html.ActionLink("Details", "Details", new {id=item.NoteId }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.NoteId })
            </td>
        </tr>
    }

</table>

@section scripts {
    <script language="javascript" type="text/javascript">
        $(document).ready(function () {
            $("i[data-toggle='star']")
                .css({ "cursor": "pointer" })
                .click(function (e) {
                    var target = $(e.target);
                    var noteId = target.attr("data-id");
                    var starSet = target.hasClass("glyphicon-star");

                    $.ajax({
                        method: starSet ? "DELETE" : "PUT",
                        url: "/api/note/" + noteId + "/star",
                        data: null
                    })
                        .done(function (r) {
                            target.removeClass();
                            target.addClass("glyphicon " + (starSet ? "glyphicon-star-empty" : "glyphicon-star"));
                        })
                        .fail(function (r) {
                            alert("Failed to change star status");
                        });
                });
        });
    </script>
}